### PR TITLE
Upgrade to the lastest PIA v.65

### PR DESCRIPTION
**Pull request by ngelx**
The main changes is to download the latest CRT from PIA instead of being inline. Also I've updated the VPN config for using that certificate (AES-128-CBC) and set the port to 1198.

If the installer is run over an old installation, i will be ask before trying to upgrade the configs. It may be a good idea to backup them ... you know, just in case ;)

### CODE REVIEW

**Comment by ngelx** [comment]
Also it may be a good idea to add tags for different versions. I've bump the version to 1.1 on this PR but  feel free to change to whatever you think is better.

**Comment by ngelx** [comment]
@shaynewang any news on this? thoughts?

**Comment by shaynewang** [comment]
@ngelx I'll probably have some time to test it this weekend. Thanks for the addition.

**Comment by ngelx** [comment]
No problem! let me know any news.

**Pull request merged**
